### ISSUE TITLE
Fix promise progress

### ISSUE THREAD

**Issue by liljimmyk99** [elmsln/haxcms-user-flow#14]

**Comment by liljimmyk99** [comment]
Get the generated button to render over the svg regardless of where it is implemented.

**Comment by btopro** [comment]
@Taylor-Bracone make this happen and not apartments

**Comment by liljimmyk99** [comment]
@Taylor-Bracone Can you make the promise-progress loading bar not do the full width of the SVG?  It looks weird when the button appears.
