### ISSUE TITLE
work on top bar of links, options, etc

### ISSUE THREAD

**Issue by btopro** [elmsln/haxcms-user-flow#22]
This is its own web component, needs a slot for adding items to left, right and center of the bar. @elizabeth-delor did some mock ups in a few places, https://www.figma.com/file/P2a9LUfwRqCF3yX1DBieeK/Variants-and-Stuff?node-id=0%3A1 included.

needs to support sound toggle, dark mode toggle, the character face (which clicking reveals menu).

Other comps have the menu options / what can be done in that area so time to start working on implementing as its own component

**Comment by btopro** [comment]
@dronk6 @Taylor-Bracone tagged you both on this cause I think the top bar is the bar + the menu which are two somewhat equal yet related yet separate pieces. Shoot for these to be the next focus

**Comment by Taylor-Bracone** [comment]
https://www.figma.com/file/P2a9LUfwRqCF3yX1DBieeK/Variants-and-Stuff?node-id=0%3A1

**Comment by Taylor-Bracone** [comment]
https://www.npmjs.com/package/@material/mwc-top-app-bar. leverage.

**Comment by btopro** [comment]
@dronk6 Talk to @elizabeth-delor next week about some SVG bg assets for the top bar. I've put it in brute force as orange but it needs designed to fit w/ the rpg vibe in subtle ways. Maybe the edge of it is actually wired JS, I don't know. I'll leave that to the two of you to envision what it looks like and then Drew to continue developing and implementing it.
