### ISSUE TITLE
Jimmy's Tasks

### ISSUE THREAD

**Issue by liljimmyk99** [elmsln/haxcms-user-flow#32]
- [x] Search bar + talk to store
- [x] Basic container for site bars (results of search)
- [x] Make button to trigger new/return user (like the reset button)
- [ ] add route/step 0 (new people: does check to see if no `site.json` return: search bar and recents render)

**Comment by liljimmyk99** [comment]
Search Bar and talking to the store and a separate results component done in commit 1c5d02c6e20b6c4f046d3b5746094e8a54ed1608

**Comment by liljimmyk99** [comment]
Make Button to trigger new/return user done in commit 547df26b14d26e69c52aa3ab8872b90f4c93ccdf

**Comment by btopro** [comment]
#41 continued here
