### ISSUE TITLE
clean up noticed from heroku deploy

### ISSUE THREAD

**Issue by btopro** [elmsln/haxcms-user-flow#86]
- [x] login needs to make sure its only there 1x
- [x] redirect to site should drop the /index.html from path
- [x] add page-break to allowed tags / default
- [x] save makes a new page (might be bc of this item above I hope)
- [x] add rpg-character as well
- [x] fonts weird sizing on modal for operations
- [x] make sure clone rewrites the id for sites (backend)
- [x] make sure frontend if multiple match, just selects the 1st one for the operation
- [x] addKeywords (hax-picker.js:80:532) -- issue with upload location (might be bc of data model change)
- [x] Delete Course - Confirmation Screen sizing issue
- [x] Finished Course Loading - Safari doesn’t support the animation
- [x] Dodging Tutorial - X on help icon says
- [x] Copying Problems - copying a site results in not being able to archive or delete
- [x] Themes: Theme names should have course/portfolio in them (Ex. `Bootstrap Portfolio Theme`, `Blog Portfolio Theme`)
- [x] Journey: Textfield starter text says `'Course Number'` or `Portfolio Name`, can still have `Create Journey` Button
- [x] Tutorial Scroll - white space when scrolling

**Comment by liljimmyk99** [comment]
Logical Flaw: There should be a something that consistently says whether you are making a course/Portfolio
**Implementation Suggestions**

- Themes: Theme names should have course/portfolio in them (Ex. Bootstrap Portfolio Theme, Blog Portfolio Theme)
- Journey: Textfield starter text says 'Course Number' or 'Portfolio Name', can still have `Create Journey` Button

**Comment by liljimmyk99** [comment]
Simple-Modal actions for `copy, download, archive, delete` the headings need more spacing in between.
<img width="745" alt="Screen Shot 2022-05-02 at 12 23 19 PM" src="https://user-images.githubusercontent.com/49504930/166269944-2255451c-807a-4b10-b736-e02f3d21723b.png">

**Comment by dronk6** [comment]
**Visual** (all minor stuff, no functionality lost)
- Home page
    - <Welcome> changes to sans serif font rather than just scaling down (only in Chrome though, it looks fine in Edge)
    - On resize, there is a weird looking space between the hax logo and the search icon. Might look better if the search icon is pushed all the way to the left with the hax logo (text-align: start; on the center div at a specific media query should fix it)
    - Tooltip is still showing on rpg-character when the system menu is open, blocking top menu option (could probably be disabled when userMenuOpen = true)
    - Tooltip for system menu is hiding offscreen on Edge

**Comment by liljimmyk99** [comment]
Simple-Tour:
If you horizontal scroll with the trackpad over the text, there it will not scroll.
If you horizontal scroll with the trackpad over the buttons at the bottom, it schools for infinity.........adding an `overflow-x: hidden` to the `/simple-popover/div[2]` inside of simple-popover causes the popup viewport to massively shrink and still has scrolling.
